version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dynamic_modules
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./modules:/app/modules

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./modules:/app/modules
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password123@db:5432/dynamic_modules
      NODE_ENV: development

volumes:
  postgres_data:
  modules: